language: php
sudo: true

addons:
  firefox: "latest-esr"
  postgresql: "9.6"

  apt:
    packages:
      - "mysql-client-5.6"
      - "mysql-client-core-5.6"
      - "mysql-server-5.6"
      - "openjdk-8-jre-headless"

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.npm"

php:
  - "7.0"
  - "7.1"
  - "7.2"

env:
  matrix:
    - MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
